name: Preview Deploy (PR)

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Set BASE_PATH for this PR
        run: echo "BASE_PATH=/portfolio/previews/pr-${{ github.event.number }}/" >> $GITHUB_ENV

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          BASE_PATH: ${{ env.BASE_PATH }}

      - name: Deploy to gh-pages/previews/pr-<N>
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: previews/pr-${{ github.event.number }}
          keep_files: true

      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request.number;
            const url = `https://f-delapaz-uat.github.io/portfolio/previews/pr-${pr}/#/`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body: `🚀 Preview ready: ${url}`
            });
